#!/usr/bin/env python3
"""
CORTEXT Output File Copier

This script copies the final HTML output file from the CORTEXT processing pipeline
to a destination directory named after the document's identity. It ensures that
each processed document has its own uniquely named output file in an appropriately
named directory.
"""

import os
import sys
import shutil
import sqlite3
import re


# Connect to the CORTEXT database
conn = sqlite3.connect("/home/ec2-user/cortext_io/cortext_io_db/cortext_io.db")
c = conn.cursor()

# Query the database to get the document identity from the first document
c.execute("SELECT identity from doc_summary where doc_id = 1")

identity = ""

# Extract the identity and clean it to create a valid filename
# This removes all non-alphabetic characters to ensure a clean directory/file name
for row in c.fetchall():
    identity = re.sub(r'[^a-z]', '', row[0])

# Define source and destination paths for the file copy operation
# Source: The standard output HTML file generated by the CORTEXT pipeline
# Destination: A document-specific directory and filename based on the document's identity
src = "/home/ec2-user/cortext_io/cortext_io_db/000_cortext_io.html"
dest = "/home/ec2-user/cortext_io/output/" + identity + "/" + identity + ".html"

# Copy the file to its final destination
# This preserves the original file while creating a document-specific copy
shutil.copyfile(src, dest)
